### ISSUE TITLE
Modify UI of "Word Definition"

### ISSUE THREAD

**Issue by SachinMittal1766** [ZeroOctave/ZeroOctave-Javascript-Projects#350]
**Is your feature request related to a problem? Please describe.**
 UI of "Word Definition" webpage is not looking good.

**Describe the solution you'd like**
I would like to change UI of webpage. I am attaching design also.

When no word is searched
![IoT-Spot (2)](https://user-images.githubusercontent.com/82721772/158023694-f4b67265-0dc0-4c73-8494-369047f60579.png)

After searching
![IoT-Spot (3)](https://user-images.githubusercontent.com/82721772/158023692-4720346f-eb89-432c-9190-fe2299662883.png)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Harshitp7** [comment]
The speaker logo for pronounciation can be set adjacent to the word instead of putting it far away to the opposite side, the font style can also be changed to fonts like Roboto. the word "Meaning" written below the searched word can be removed to give a better look. The part of speech specified below the word searched (in this case "noun") can be put in brackets in italics font. I want this issue to be assigned, I am a GSSoC'22 contributor.

**Comment by sreelakshmig009** [comment]
@Harshitp7 I have assigned this issue to the issue creator. Feel free to create new issues or resolve any bugs
